import { type SchemaTypeDefinition } from "sanity"

import { author, hygiene, landing, page, post, tag } from "./schemas/documents"
import { redirectType } from "./schemas/documents/redirects"
import {
  accordion,
  accordionItem,
  aside,
  blockContent,
  buttonBlock,
  card,
  cardLogo,
  cards,
  cardsLogo,
  cardSmall,
  cardsSmall,
  cardsStat,
  cardsSticky,
  cardStat,
  cardSticky,
  cardsTimeline,
  cardTimeline,
  connectedCard,
  customUrl,
  ecosystemCard,
  faq,
  faqs,
  header,
  homeBuild,
  homeConnected,
  homeEcosystem,
  homeHero,
  homeNetwork,
  homeStats,
  homeVideo,
  lineBreak,
  mediaBlock,
  menu,
  menuItem,
  meta,
  pageBuilder,
  quote,
  sideBySide,
  smallHomeCard,
  socialLink,
  statsCard,
  video,
  youtube,
} from "./schemas/objects"
import {
  blog,
  footer,
  home,
  navigation,
  notfound,
  pressReleases,
} from "./schemas/singletons"

const documentTypes = [tag, author, post, landing, page, hygiene, redirectType]
const objectTypes = [
  youtube,
  meta,
  faq,
  faqs,
  accordion,
  accordionItem,
  buttonBlock,
  card,
  cards,
  cardSmall,
  cardsSmall,
  cardSticky,
  cardsSticky,
  cardsLogo,
  cardLogo,
  cardsStat,
  cardStat,
  customUrl,
  header,
  pageBuilder,
  blockContent,
  lineBreak,
  mediaBlock,
  menu,
  menuItem,
  sideBySide,
  socialLink,
  aside,
  video,
  cardTimeline,
  cardsTimeline,
  quote,
  homeHero,
  homeVideo,
  homeConnected,
  connectedCard,
  homeEcosystem,
  ecosystemCard,
  homeStats,
  statsCard,
  homeNetwork,
  smallHomeCard,
  homeBuild,
]

const singletons = [footer, navigation, notfound, home, blog, pressReleases]

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [...documentTypes, ...objectTypes, ...singletons],
}
