name: Mozilla Observatory Scan

on:
  push:
    # branches:
    #   - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  observatory-scan:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_URL: "https://polkadot.com"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install tsx
        run: npm install -g tsx

      - name: Run Mozilla Observatory Scan and save to file
        run: |
          result=$(tsx ./scripts/observatory-scan.mts)
          echo "$result" > observatory.md
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$result" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: observatory-scan-result
          path: observatory.md
